"use strict";
exports.__esModule = true;
var masajista_1 = require("./masajista");
var entrenador_1 = require("./entrenador");
var futbolista_1 = require("./futbolista");
var messi = new futbolista_1.Futbolista("Leonel", "Messi", 12444370, 10 - 5 - 1999);
var enzo = new masajista_1.Masajista("Enzo", "bustos", 33123478, 12 - 6 - 1870, "quinesiologo");
var bautista = new entrenador_1.Entrenador("Bautista", "lopez", 33012333, 3 - 23 - 4545);
console.log(messi.goles());
enzo.getCertificado();
console.log(bautista.titulosObtenidos());
messi.getNacimiento;
