"use strict";
exports.__esModule = true;
var masajista_1 = require("./masajista");
var entrenador_1 = require("./entrenador");
var futbolista_1 = require("./futbolista");
var fecha = new Date("10-02-1990");
var messi = new futbolista_1.Futbolista("Leonel", "Messi", 12444370, fecha);
var enzo = new masajista_1.Masajista("Enzo", "bustos", 33123478, fecha, "quinesiologo");
var bautista = new entrenador_1.Entrenador("Bautista", "lopez", 33012333, fecha);
console.log(messi.goles());
console.log(enzo.getCertificado());
console.log(bautista.titulosObtenidos());
